### ISSUE TITLE
olx.ro issue

### ISSUE THREAD

**Issue by afATRWTtdgsdfys** [episage/next-page-chrome-extension#3]
Hi there,

 I've been meaning to get this rule working with this romanian marketplace site, but I can't seem to get it to work.

URL: 

> https://www.olx.ro/oferte/q-boxe/?search%5Bphotos%5D=1&search%5Border%5D=filter_float_price%3Aasc&search%5Bfilter_float_price%3Afrom%5D=5&search%5Bfilter_float_price%3Ato%5D=100&view=list&page=1

Rule:

```
url ^https://www\.olx\.ro/oferte/
pageElement //tr[@class="wrap"]
nextLink //span[(text()="Urmatoarele anunturi »")]
```

Can you give me any hints on how to fix this? 

Thanks!

**Comment by episage** [comment]
I fixed this in v1.1.1. Published and pending review in Chrome Web Store.
